<?php
/**
 * @file
 */

/**
 * Implements hook_views_default_views_alter().
 */
function imagex_answers_views_default_views_alter(&$views) {
  if (isset($views['answers_to_a_question'])) {
    // Remove the "No answers yet".
    $views['answers_to_a_question']->display['default']->handler->display->display_options['empty'] = array();
  }
}

/**
 * Implements hook_menu().
 */
function imagex_answers_menu() {
  $items['linux-answers/%ctools_js/select-answer/%node/%'] = array(
    'title' => 'Select Answer',
    'page callback' => 'imagex_answer_select_answer',
    'page arguments' => array(1, 3, 4),
    'access callback' => 'node_access',
    'access arguments' => array('update', 3),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_form_alter().
*/
function imagex_answers_form_alter(&$form, &$form_state, $form_id) {
  if($form_id == 'answer_node_form') {
    $form['title']['#type'] = 'hidden';
    $form['title']['#default_value'] = $form['field_answer_question']['en'][0]['nid']['#title'];
  }
}

/**
 * Implements hook_node_view().
 */
function imagex_answers_node_view($node, $view_mode, $langcode) {
  global $user;
  if ($node->type == 'answer') {
    $qid = $node->field_answer_question[LANGUAGE_NONE][0]['nid'];
    $q_node = node_load($qid);
    $chosen = isset($q_node->field_chosen_answer[LANGUAGE_NONE][0]['nid']) ? $q_node->field_chosen_answer[LANGUAGE_NONE][0]['nid'] : 0;
    if (node_access('update', $q_node, $user) && !$chosen) {
      drupal_add_library('system', 'drupal.ajax');
      // if the user has access to edit the question node (they are the author or admin)
      // then we let have access to the node link to select the answer.
      $node->content['links']['#links']['answer'] = array(
        'href' => 'linux-answers/nojs/select-answer/' . $qid . '/' . $node->nid,
        'title' => t('Select This Answer'),
        'attributes' => array(
          'class' => array(
            'use-ajax',
            'flag-linux-answer-select-' . $qid,
          ),
          'id' => 'flag-linux-answer-select-' . $qid . '-' . $node->nid,
          'alt' => t('Select this as the best answer and close this question'),
        ),
      );
    }
    if ($chosen == $node->nid) {
      $node->content['links']['#links']['answer'] = array(
        'title' => '<span class="best-answer">' . t('Best Answer') . '</span>',
        'html' => TRUE,
      );
    }
  }
}

/**
 * This function updates the node with answer nid
 */
function imagex_answer_select_answer($js, $node, $answer_nid) {
  // Save the selected answer and lock the question
  $node->field_chosen_answer[LANGUAGE_NONE][0]['nid'] = $answer_nid;
  $node->field_question_locked_p[LANGUAGE_NONE][0]['value'] = 1;
  node_save($node);
  if ($js) {
    // Ajax commands here
    $best = '<span class="best-answer">' . t('Best Answer') . '</span>';
    ctools_include('ajax');
    $commands = array();
    // replace the selected link with some text designating it as the selected answer
    $commands[] = ajax_command_replace('#flag-linux-answer-select-' . $node->nid . '-' . $answer_nid, $best);
    // remove any of the links on other answers
    $commands[] = ajax_command_remove('.flag-linux-answer-select-' . $node->nid);
    //Remove any answer forms that are on the page.
    $commands[] = ajax_command_remove('#answer-node-form-pane'); //This is the ID that should be given to panes inorder to be removed
    $commands[] = ajax_command_remove('#answer-node-form');

    print ajax_render($commands); // this function exits.
    exit;
  }
  else {
    // Simply redirect back to the question page
    drupal_goto('node/' . $node->nid);
  }
}
